name: Package and push to registry repo
on:
  push:
    tags: [ v* ]
  workflow_dispatch:

env:
  # the repository to which to push the release version
  # usually a fork of typst/packages (https://github.com/typst/packages/)
  # that you have push privileges to
  REGISTRY_REPO: JeppeKlitgaard/typst-packages
  # the path within that repo where the "<name>/<version>" directory should be put
  # for the Typst package registry, keep this as is
  PATH_PREFIX: packages/preview

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-binstall

      - name: Install Rust tooling
        run:
          cargo binstall -y oxipng

      - name: Setup typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: latest

      - name: Determine and check package metadata
        run: |
          . scripts/setup
          echo "PKG_NAME=${PKG_PREFIX}" >> "${GITHUB_ENV}"
          echo "PKG_VERSION=${VERSION}" >> "${GITHUB_ENV}"

          if [[ "${GITHUB_REF_NAME}" != "v${VERSION}" ]]; then
            echo "package version ${VERSION} does not match release tag ${GITHUB_REF_NAME}" >&2
            exit 1
          fi

      - name: Build package
        run: |
          just install-preview
          just install-fonts
          just thumbnail
          just package package

      - name: Checkout package registry
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REGISTRY_REPO }}
          token: ${{ secrets.REGISTRY_TOKEN }}
          path: typst-packages

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          zip -r "release-assets/${PKG_NAME}-${PKG_VERSION}.zip" "package"
          zip -r "release-assets/fonts.zip" "fonts"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.PKG_NAME }} ${{ env.PKG_VERSION }}
          generate_release_notes: true
          files: |
            release-assets/*

      # - name: Release package on Typst package registry
      #   run: |
      #     mkdir -p "typst-packages/${{ env.PATH_PREFIX }}/$PKG_NAME"
      #     mv "package/${PKG_NAME}/${PKG_VERSION}" "typst-packages/${{ env.PATH_PREFIX }}/${PKG_NAME}"
      #     rmdir "package/${PKG_NAME}"
      #     rmdir package

      #     GIT_USER_NAME="$(git log -1 --pretty=format:'%an')"
      #     GIT_USER_EMAIL="$(git log -1 --pretty=format:'%ae')"

      #     cd typst-packages
      #     git config user.name "${GIT_USER_NAME}"
      #     git config user.email "${GIT_USER_EMAIL}"
      #     git checkout -b "${PKG_NAME}-${PKG_VERSION}"
      #     git add .
      #     git commit -m "${PKG_NAME}:${PKG_VERSION}"
      #     git push --force --set-upstream origin "${PKG_NAME}-${PKG_VERSION}"
